name: pigeon_generator_example
description: Example of how to use pigeon_generator
publish_to: none

environment: 
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  pigeon: ^26.0.0
  pigeon_generator:
    path: ../
