name: pigeon_generator_example
description: Example of how to use pigeon_generator
publish_to: none

environment: 
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  pigeon: ^25.1.0
  pigeon_generator:
    path: ../
