name: pigeon_generator_example
description: Example of how to use pigeon_generator
publish_to: none

environment: 
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.1
  pigeon_generator:
    path: ../
