import 'package:path/path.dart' show normalize;

/// Configuration for the output file generated by Pigeon.
class OutputConfig {
  OutputConfig._internal(
    String path, {
    required this.extension,
    this.pascalCase = false,
    this.append,
  }) : path = normalize(path.trim());

  // The path to the output directory.
  final String path;

  // The extension of the generated file.
  final String extension;

  // Whether to use PascalCase for the generated file name.
  final bool pascalCase;

  // The string to append to the name of the generated file.
  final String? append;

  /// Returns [OutputConfig] from the given options, or null if path is null.
  static OutputConfig? fromOptions(
    String? path, {
    required String extension,
    bool pascalCase = false,
    String? append,
  }) {
    if (path == null) return null; // Return null if path is null.

    return OutputConfig._internal(
      path,
      extension: extension,
      pascalCase: pascalCase,
      append: append,
    );
  }
}
