name: Test dart code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get --no-example

      - name: Run tests
        run: dart test --concurrency=1
